[package]
name = "indexer-explorer"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tracing-subscriber = "0.2.4"

near-indexer = { path = "../../chain/indexer" }